version: "3.9"

services:
    php:
        container_name: php
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PHP_PORT}:80"

    db:
      image: mariadb:10.6
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - ${SQL_PORT}:80
      environment:
        - PMA_ARBITRARY=1