version: "3.9"

services:
    php:
        container_name: php
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "8089:80"

    db:
      image: mariadb:10.6
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 121212Err

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8090:80
      environment:
        - PMA_ARBITRARY=1